export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'; 
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED'; 
export const SET_AUTH_PROFILE = 'SET_AUTH_PROFILE'; 

export const GET_USER_TRANSACTIONS = 'GET_USER_TRANSACTIONS' ; 
export const GET_USER_TRANSACTIONS_SUCCESS = 'GET_USER_TRANSACTIONS_SUCCESS' ; 
export const GET_USER_TRANSACTIONS_FAILED = 'GET_USER_TRANSACTIONS_FAILED' ; 