export const GET_PROFILE = 'GET_PROFILE'; 
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'; 

export const GET_USER_TRANSACTIONS = 'GET_USER_TRANSACTIONS' ; 
export const GET_USER_CATEGORIES = 'GET_USER_CATEGORIES' ; 
export const GET_USER_TRANSACTIONS_SUCCESS = 'GET_USER_TRANSACTIONS_SUCCESS' ; 
export const GET_USER_TRANSACTIONS_FAILED = 'GET_USER_TRANSACTIONS_FAILED' ; 
export const FLATTEN_TRANSACTION_DATA = 'FLATTEN_TRANSACTION_DATA'; 
export const GET_ALL_USERS = 'GET_ALL_USERS'; 

export const GET_ROOMATE_REQUESTS = 'GET_ROOMATE_REQUESTS'; 
export const GET_ROOMATES = 'GET_ROOMATES'; 
export const SET_FOCUSED_ROOMMATE = 'SET_FOCUSED_ROOMMATE'; 
export const GET_ROOMATE_TRANS_FROM = 'SET_ROOMATE_TRANS_FROM'; 

export const CHANGE_TRANSACTION_DATES = 'CHANGE_TRANSACTION_DATES';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'; 