export const GET_PROFILE = 'GET_PROFILE'; 
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'; 

export const GET_USER_TRANSACTIONS = 'GET_USER_TRANSACTIONS' ; 
export const GET_USER_TRANSACTIONS_SUCCESS = 'GET_USER_TRANSACTIONS_SUCCESS' ; 
export const GET_USER_TRANSACTIONS_FAILED = 'GET_USER_TRANSACTIONS_FAILED' ; 
export const FLATTEN_TRANSACTION_DATA = 'FLATTEN_TRANSACTION_DATA'; 